# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gorras M
email: pacoman871@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: GorrasM°
address_line: Av.Sonora 63, Col.Roma Nte., 06700, Ciudad de México, CDMX
telephone_number: 1.800.245.356
fax_number: 1.800.245.357
company_email: hello@LawOffice.org
google_map: https://www.google.com/maps/place/New+Era+Store+Condesa/@19.4182631,-99.2379463,13z/data=!3m1!5s0x85d1ff46153cb5bf:0x4fcb1993cc07a3f2!4m10!1m2!2m1!1snew+era!3m6!1s0x85d1ff98890552c1:0x5d6c07c7f72e1b7a!8m2!3d19.4182633!4d-99.1720334!15sCgduZXcgZXJhWgkiB25ldyBlcmGSAQ5jbG90aGluZ19zdG9yZeABAA!16s%2Fg%2F11qpwzkcd4

# Social Link
facebook_link: https://www.facebook.com/daddyyankee
twitter_link: https://twitter.com/NewEraMx
linkedin_link: https://www.youtube.com/watch?v=Sg4bDBCSaMA&list=RDRMl7Fx-WNy4&index=2
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
